# This is a basic workflow to help you get started with Actions

name: DeFog-Benchmarks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'framework/workload/DockerImages/yolo/Dockerfile'
      - 'framework/workload/DockerImages/yolo/*.sh'
      - 'framework/workload/DockerImages/Pocketsphinx/Dockerfile'
      - 'framework/workload/DockerImages/Pocketsphinx/*.sh'
      - 'framework/workload/DockerImages/Aeneas/Dockerfile'
      - 'framework/workload/DockerImages/Aeneas/*.sh'
      - '.github/workflows/*.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the Yolo image
          run: docker build -t shreshthtuli/yolo framework/workload/DockerImages/yolo/
        - name: Push the yolo image
          run: docker push shreshthtuli/yolo
        - name: Build the PocketSphinx image
          run: docker build -t shreshthtuli/pocketsphinx framework/workload/DockerImages/PocketSphinx/
        - name: Push the PocketSphinx image
          run: docker push shreshthtuli/pocketsphinx
        - name: Build the Aeneas image
          run: docker build -t shreshthtuli/aeneas framework/workload/DockerImages/Aeneas/
        - name: Push the Aeneas image
          run: docker push shreshthtuli/aeneas
